
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView inputField;

	private global::Gtk.Button button1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView outputField;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView languageText;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.CheckButton checkbutton2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 350;
		this.GtkScrolledWindow.HeightRequest = 100;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.inputField = new global::Gtk.TextView();
		this.inputField.CanFocus = true;
		this.inputField.Name = "inputField";
		this.GtkScrolledWindow.Add(this.inputField);
		this.fixed3.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow]));
		w2.X = 10;
		w2.Y = 10;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Translate");
		this.fixed3.Add(this.button1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
		w3.X = 16;
		w3.Y = 120;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.WidthRequest = 350;
		this.GtkScrolledWindow1.HeightRequest = 100;
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.outputField = new global::Gtk.TextView();
		this.outputField.CanFocus = true;
		this.outputField.Name = "outputField";
		this.GtkScrolledWindow1.Add(this.outputField);
		this.fixed3.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow1]));
		w5.X = 10;
		w5.Y = 160;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.WidthRequest = 30;
		this.GtkScrolledWindow2.HeightRequest = 30;
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.languageText = new global::Gtk.TextView();
		this.languageText.Buffer.Text = global::Mono.Unix.Catalog.GetString("ru");
		this.languageText.CanFocus = true;
		this.languageText.Name = "languageText";
		this.GtkScrolledWindow2.Add(this.languageText);
		this.fixed3.Add(this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow2]));
		w7.X = 94;
		w7.Y = 124;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("always on top");
		this.checkbutton1.Active = true;
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed3.Add(this.checkbutton1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.checkbutton1]));
		w8.X = 136;
		w8.Y = 125;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString("clear field");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed3.Add(this.checkbutton2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.checkbutton2]));
		w9.X = 251;
		w9.Y = 123;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 369;
		this.DefaultHeight = 280;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.checkbutton1.Toggled += new global::System.EventHandler(this.OnCheckbutton1Toggled);
	}
}
